"use strict";

const REASON_CODES = Object.freeze([
  "CF_INPUT_INVALID",
  "CF_POLICY_INVALID",
  "CF_TARGET_INVALID",
  "CF_STACK_INPUT_INVALID",
  "CF_STACK_DECISION_MISSING",
  "CF_STACK_DECISION_BLOCKED",
  "CF_STACK_RUNTIME_UNSUPPORTED",
  "CF_STACK_UI_LIBRARY_NONE",
  "CF_COMPONENT_INPUT_INVALID",
  "CF_COMPONENT_RESOLUTION_MISSING",
  "CF_COMPONENT_RESOLUTION_BLOCKED",
  "CF_COMPONENT_VERIFICATION_MISSING",
  "CF_COMPONENT_VERIFICATION_BLOCKED",
  "CF_COMPONENT_BASELINE_ROLE_MISSING",
  "CF_COMPONENT_ORIGIN_INVALID",
  "CF_COMPONENT_SOURCE_MISSING",
  "CF_COMPONENT_SYMBOL_MISSING",
  "CF_COMPONENT_CONTRACT_MISSING",
  "CF_COMPONENT_TOKEN_EVIDENCE_MISSING",
  "CF_COMPONENT_KEYBOARD_EVIDENCE_MISSING",
  "CF_COMPONENT_FOCUS_EVIDENCE_MISSING",
  "CF_COMPONENT_STATE_EVIDENCE_MISSING",
  "CF_COMPONENT_PLAYGROUND_EVIDENCE_MISSING",
  "CF_COMPONENT_PAGE_EVIDENCE_MISSING",
  "CF_PLAYGROUND_INPUT_INVALID",
  "CF_PLAYGROUND_RECEIPT_MISSING",
  "CF_PLAYGROUND_RECEIPT_BLOCKED",
  "CF_PLAYGROUND_WAIVER_NOT_ALLOWED",
  "CF_PLAYGROUND_PROFILE_MISMATCH",
  "CF_PAGE_INPUT_INVALID",
  "CF_PAGE_USAGE_MISSING",
  "CF_PAGE_ROUTE_MISSING",
  "CF_PAGE_REQUIRED_ROLE_MISSING",
  "CF_PAGE_COMPONENT_IDENTITY_MISMATCH",
  "CF_PAGE_COMPONENT_NOT_RENDERED",
  "CF_PAGE_COMPONENT_HIDDEN",
  "CF_PAGE_READINESS_MISSING",
  "CF_PAGE_READINESS_SCOPE_MISMATCH",
  "CF_EVIDENCE_INPUT_INVALID",
  "CF_EVIDENCE_MISSING",
  "CF_EVIDENCE_PATH_INVALID",
  "CF_EVIDENCE_FILE_MISSING",
  "CF_EVIDENCE_HASH_INVALID",
  "CF_EVIDENCE_HASH_MISMATCH",
  "CF_EVIDENCE_PNG_INVALID",
  "CF_EVIDENCE_PNG_DIMENSIONS_INVALID",
  "CF_EVIDENCE_PNG_TRANSPARENCY_INVALID",
  "CF_EVIDENCE_REFERENCE_MISSING",
]);

const order = new Map(REASON_CODES.map((code, index) => [code, index]));

function assertReasonCode(code) {
  if (!order.has(code)) throw new Error(`component-first reason code is not registered: ${String(code)}`);
  return code;
}

function sortReasonCodes(codes = []) {
  return [...new Set(codes.map(assertReasonCode))].sort((left, right) => order.get(left) - order.get(right));
}

module.exports = { REASON_CODES, assertReasonCode, sortReasonCodes };
