"use strict";

const assert = require("node:assert/strict");
const test = require("node:test");
const fs = require("node:fs");
const path = require("node:path");
const { applyPatch, checkCounter, checkGolden, listCases, loadCase, validateCase } = require("../evals/cases/cases.cjs");

const repoRoot = path.resolve(__dirname, "..");
const casesRoot = path.join(repoRoot, "evals/cases");
const cases = listCases(casesRoot).map(loadCase);

test("the library has golden cases for product PV, logo sting, UI promo, explainer and MAD", () => {
  const types = new Set(cases.map((entry) => entry.spec.deliverableType));
  for (const type of ["product-pv", "logo-sting", "ui-promo", "explainer", "mad"]) assert.ok(types.has(type), type);
});

// Captures and generated art are regenerated by each case's script and must stay out of git.
function assertUntracked(entry, assets) {
  const { spawnSync } = require("node:child_process");
  const dir = path.relative(repoRoot, path.join(entry.dir, assets.dir)).split(path.sep).join("/");
  const tracked = spawnSync("git", ["ls-files", "--", dir], { cwd: repoRoot, encoding: "utf8" });
  assert.equal(tracked.status, 0, tracked.stderr);
  assert.equal(tracked.stdout.trim(), "", `${dir} must not be committed`);
  const ignored = spawnSync("git", ["check-ignore", "-q", `${dir}/${assets.files[0]}`], { cwd: repoRoot });
  assert.equal(ignored.status, 0, `${dir} must be git-ignored`);
}

test("third-party interface captures are declared with a pinned source and never committed", () => {
  const captured = cases.filter((entry) => entry.spec.golden.captures);
  assert.ok(captured.length >= 1);
  for (const entry of captured) assertUntracked(entry, entry.spec.golden.captures);
});

test("generated art is declared with its script and tool and never committed", () => {
  const generated = cases.filter((entry) => entry.spec.golden.generated);
  assert.ok(generated.length >= 1);
  for (const entry of generated) assertUntracked(entry, entry.spec.golden.generated);
  const spec = structuredClone(generated[0].spec);
  delete spec.golden.generated.tool;
  assert.throws(() => validateCase(spec, generated[0].dir), /golden\.generated\.tool/);
});

test("every golden passes the storyboard, score and timeline gates", () => {
  for (const entry of cases) {
    const result = checkGolden(entry);
    assert.ok(result.passed, `${entry.spec.id}: ${result.codes.join(", ")}`);
  }
});

test("every storyboard and timeline counter-example is caught with the codes it names, which the golden does not have", () => {
  let checked = 0;
  for (const entry of cases) {
    const golden = checkGolden(entry);
    for (const counter of entry.spec.counterExamples.filter((item) => item.target !== "render")) {
      const result = checkCounter(entry, counter);
      assert.deepEqual(result.missing, [], `${entry.spec.id}/${counter.id} got ${result.codes.join(", ")}`);
      assert.deepEqual(counter.expect.filter((code) => golden.codes.includes(code)), [], `${entry.spec.id}/${counter.id} expects a code the golden already has`);
      checked += 1;
    }
  }
  assert.ok(checked >= 8, `only ${checked} counter-examples checked`);
});

test("counter-examples cover every failure class across the library", () => {
  const classes = new Set(cases.flatMap((entry) => entry.spec.counterExamples.map((counter) => counter.failureClass)));
  for (const failureClass of ["workflow", "tool-misuse", "generic-concept", "rough-execution", "taste-gap"]) assert.ok(classes.has(failureClass), failureClass);
});

test("the golden cases stay out of the shipped package", () => {
  const resources = JSON.parse(fs.readFileSync(path.join(repoRoot, "skill/references/package-resources.json"), "utf8"));
  assert.equal(resources.packageRoot, "skill");
  assert.ok(path.relative(path.join(repoRoot, resources.packageRoot), casesRoot).startsWith(".."), "evals/cases must live outside the package root");
  assert.ok(!resources.required.some((file) => /golden|evals\/cases/.test(file)));
});

test("case validation rejects approvals without a watched render, and gate rules without a counter-example", () => {
  const entry = cases[0];
  const spec = structuredClone(entry.spec);
  spec.status = "approved";
  spec.approval = { verdict: "accept", by: "user", date: "2026-09-29", note: "ok" };
  assert.throws(() => validateCase(spec, entry.dir), /renderSha256/);
  const orphan = structuredClone(entry.spec);
  orphan.rules.push({ id: "orphan", choice: "c", rule: "r", fix: "f", enforcedBy: { kind: "gate", gate: "timeline", codes: ["layout-tween"] } });
  assert.throws(() => validateCase(orphan, entry.dir), /no counter-example exercises it/);
});

test("patch operations select tweens by value and refuse stale selectors", () => {
  const timeline = { tweens: [{ targets: ["#a"], startSec: 1, props: ["x"] }, { targets: ["#b"], startSec: 2, props: ["y"] }] };
  const updated = applyPatch(timeline, [{ op: "update-where", path: "/tweens", match: { targets: ["#b"], startSec: 2.0001 }, set: { props: ["width"] } }]);
  assert.deepEqual(updated.tweens[1].props, ["width"]);
  assert.deepEqual(timeline.tweens[1].props, ["y"], "the golden is not mutated");
  assert.equal(applyPatch(timeline, [{ op: "remove-where", path: "/tweens", match: { targets: ["#a"] } }]).tweens.length, 1);
  assert.throws(() => applyPatch(timeline, [{ op: "remove-where", path: "/tweens", match: { targets: ["#c"] } }]), /matched nothing/);
  assert.throws(() => applyPatch(timeline, [{ op: "replace", path: "/missing", value: 1 }]), /nothing to replace/);
});
